server/webapp/WEB-INF/rails/config/routes.rb
##########################GO-LICENSE-START################################
# Copyright 2018 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################GO-LICENSE-END##################################

Rails.application.routes.draw do
  unless defined?(CONSTANTS)
    CONFIG_REPO_ID_FORMAT = ROLE_NAME_FORMAT = ELASTIC_AGENT_PROFILE_ID_FORMAT = USER_NAME_FORMAT = GROUP_NAME_FORMAT = TEMPLATE_NAME_FORMAT = PIPELINE_NAME_FORMAT = STAGE_NAME_FORMAT = ENVIRONMENT_NAME_FORMAT = /[\w\-][\w\-.]*/
    JOB_NAME_FORMAT = /[\w\-.]+/
    PIPELINE_COUNTER_FORMAT = STAGE_COUNTER_FORMAT = /-?\d+/
    NON_NEGATIVE_INTEGER = /\d+/
    PIPELINE_LOCATOR_CONSTRAINTS = {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}
    STAGE_LOCATOR_CONSTRAINTS = {:stage_name => STAGE_NAME_FORMAT, :stage_counter => STAGE_COUNTER_FORMAT}.merge(PIPELINE_LOCATOR_CONSTRAINTS)
    ENVIRONMENT_NAME_CONSTRAINT = {:name => ENVIRONMENT_NAME_FORMAT}
    MERGED_ENVIRONMENT_NAME_CONSTRAINT = {:environment_name => ENVIRONMENT_NAME_FORMAT}
    PLUGIN_ID_FORMAT = /[\w\-.]+/
    ALLOW_DOTS = /[^\/]+/
    CONSTANTS = true
  end

  # This is used to generate _url and _path in application_helper#url_for_path
  get '/', to: redirect('/go/pipelines'), as: :root

  get "about", controller: :about, action: :show, as: :about

  get "admin/pipelines/snippet" => "admin/pipelines_snippet#index", as: :pipelines_snippet
  get "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_show
  get "admin/pipelines/snippet/:group_name/edit" => "admin/pipelines_snippet#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_edit
  put "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_update

  get 'admin/backup' => 'admin/backup#index', as: :backup_server
  post 'admin/backup' => 'admin/backup#perform_backup', as: :perform_backup

  ["svn", "git", "hg", "p4", "dependency", "tfs", "package"].each do |material_type|
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/new" => "admin/materials/#{material_type}#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_new"
    post "admin/pipelines/:pipeline_name/materials/#{material_type}" => "admin/materials/#{material_type}#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_create"
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print/edit" => "admin/materials/#{material_type}#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_edit"
    put "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print" => "admin/materials/#{material_type}#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_update"
  end
  defaults :no_layout => true do
    get "admin/pipelines/:pipeline_name/materials/dependency/pipeline_name_search" => "admin/materials/dependency#pipeline_name_search", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_pipeline_name_search
    get "admin/pipelines/:pipeline_name/materials/dependency/load_stage_names_for" => "admin/materials/dependency#load_stage_names_for", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_load_stage_names_for
  end
  get "admin/:stage_parent/:pipeline_name/materials" => "admin/materials#index", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_index
  delete "admin/:stage_parent/:pipeline_name/materials/:finger_print" => "admin/materials#destroy", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_delete

  get "admin/pipeline/new" => "admin/pipelines#new", as: :pipeline_new
  post "admin/pipelines" => "admin/pipelines#create", as: :pipeline_create
  get "admin/pipeline/:pipeline_name/clone" => "admin/pipelines#clone", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pipeline_clone
  post "admin/pipeline/save_clone" => "admin/pipelines#save_clone", as: :pipeline_save_clone
  get "admin/pipelines/:pipeline_name/pause_info.json" => "admin/pipelines#pause_info", :format => "json", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pause_info_refresh
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#edit", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#update", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_update

  get "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_listing
  put "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#use_template", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_use_template
  get "admin/:stage_parent/:pipeline_name/stages/new" => "admin/stages#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_new
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name" => "admin/stages#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_delete
  post "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/increment" => "admin/stages#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_edit
  #put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT,  stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update

server/webapp/WEB-INF/rails/app/views/new_navigation_elements/_dropdown_admin.html.erb
<li role="presentation">
  <%= link_to "Pipelines", pipeline_groups_path -%>
</li>
<li role="presentation">
  <%= link_to "Environments", environments_path -%>
</li>
<li role="presentation">
  <%= link_to "Templates", templates_path -%>
</li>
<li role="presentation">
  <%= link_to 'Elastic Agent Profiles', '/go/admin/elastic_profiles' -%>
</li>
<li role="presentation">
  <%= link_to 'Artifact Stores', '/go/admin/artifact_stores' -%>
</li>
<li role="presentation">
  <%= link_to "Config XML", config_view_path -%>
</li>
<li role="presentation">
  <%= link_to 'Data Sharing', '/go/admin/data_sharing/settings' -%>
</li>
<li role="presentation">
  <%= link_to "Server Configuration", edit_server_config_path -%>
</li>
<li role="presentation">
  <%= link_to "User Summary", user_listing_path -%>
</li>
<li role="presentation">
  <%= link_to "Backup", backup_server_path -%>
</li>
<li role="presentation">
  <%= link_to "Plugins", '/go/admin/plugins' -%>
</li>
<li role="presentation">
  <%= link_to "Package Repositories", package_repositories_new_path -%>
</li>
<li class="opens-right" role="presentation">
  <a href="#">Security</a>
  <ul class="menu">
    <li role="presentation">
      <%= link_to "Authorization Configuration", '/go/admin/security/auth_configs' -%>
    </li>
    <li role="presentation">
      <%= link_to "Role Configuration", '/go/admin/security/roles' -%>
    </li>
  </ul>
</li>

server/webapp/WEB-INF/rails/app/views/new_navigation_elements/_dropdown_pipeline_group_admin.html.erb
<li role="presentation">
  <%= link_to "Pipelines", pipeline_groups_path -%>
</li>
<li role="presentation">
  <%= link_to "Templates", templates_path -%>
</li>
<li role="presentation">
  <%= link_to 'Elastic Agent Profiles', '/go/admin/elastic_profiles' -%>
</li>
<li role="presentation">
  <%= link_to "Config XML", pipelines_snippet_path -%>
</li>
<li role="presentation">
  <%= link_to "Plugins", '/go/admin/plugins' -%>
</li>
<li role="presentation">
  <%= link_to "Package Repositories", package_repositories_new_path -%>
</li>

server/webapp/WEB-INF/rails/app/views/new_navigation_elements/_footer.html.erb
<footer class="app-footer">
    <div class="row expanded">
        <div class="small-12 medium-6 large-8 columns">
            <p class="copyright">Copyright &copy; <%= copyright_year %>
                <a href="https://www.thoughtworks.com/products" target='_blank'>ThoughtWorks, Inc.</a>
                Licensed under <%= link_to('Apache License, Version 2.0', "https://www.apache.org/licenses/LICENSE-2.0", :target => '_blank') -%>.<br/>
                Go includes <%= link_to('third-party software', "/go/assets/dependency-license-report-#{full_version}", :target => '_blank') -%>.
                Go Version: <%= version %>.
            </p>

        </div>
      <div class="small-12 medium-6 large-4 columns">
            <span class="inline-list social">
                <a href="https://twitter.com/goforcd" title="twitter" class="twitter"  target="_blank"></a>
                <a href="https://github.com/gocd/gocd" title="github" class="github" target="_blank"></a>
                <a href="https://groups.google.com/d/forum/go-cd" title="forums" class="forums" target="_blank"></a>
                <a href="https://docs.gocd.org/<%= unformatted_version %>" title="documentation" class="documentation" target="_blank"></a>
                <a href="https://www.gocd.org/plugins/" title="plugins" class="plugins" target="_blank"></a>
                <a href="https://api.gocd.org/<%= unformatted_version %>" title="api" class="api" target="_blank"></a>
                <a href="<%= about_path %>" title="about" class="server-details" target="_blank"></a>
                <a href="<%= cctray_path %>" title="cctray" class="cctray" target="_blank"></a>
            </span>
      </div>
  </div>
</footer>

server/webapp/WEB-INF/rails/app/views/new_navigation_elements/_navigation.html.erb
<div class="top-bar">

  <div class="medium-6 columns">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>

        <li class="menu-text"><%= link_to '', pipeline_dashboard_path, class: 'logo' -%></li>

        <li><%= link_to 'Pipelines', pipeline_dashboard_path -%></li>
        <li><%= link_to 'Agents', '/go/agents' -%></li>
        <% with_analytics_dashboard_support do %>
            <li><%= link_to 'Analytics', analytics_path -%></li>
        <% end %>
        <li>
          <% unless can_view_admin_page? -%>
              <span>Admin</span>
          <% else -%>
              <a href="#" onclick="return false;">Admin</a>
              <ul class="menu vertical admin-dropdown">
                <%- if is_user_an_admin? -%>
                    <%= render partial: 'new_navigation_elements/dropdown_admin' -%>
                <%- elsif is_user_a_group_admin? -%>
                    <%= render partial: 'new_navigation_elements/dropdown_pipeline_group_admin' -%>
                <%- elsif is_user_authorized_to_view_templates? -%>
                    <li role="presentation">
                      <%= link_to 'Templates', templates_path -%>
                    </li>
                <%- end -%>
              </ul>
          <%- end -%>
        </li>
      </ul>
    </div>
  </div>
  <div class="medium-6 columns">
    <div class="top-bar-right">
      <ul class="dropdown menu current-user nav-right" data-dropdown-menu>
        <li class="server-health-summary"><!-- filled in later by mithril --></li>
        <li><%= link_to('Need Help?', 'https://gocd.org/help', :target => '_blank') %></li>
        <% unless @user.anonymous? %>
            <li class="current-user">
              <a href="#" onclick="return false;"><i class="user"></i><%= @user.display_name %></a>
              <ul class="menu vertical">
                <li><%= link_to 'Preferences', preferences_notifications_path %></li>
                <li><%= link_to 'Sign out', url_for_path('auth/logout') %></li>
              </ul>
            </li>
        <% end %>
      </ul>
      <div id="system-notifications" class="system-notifications"></div>
    </div>
  </div>
</div>